version: "2.4"

services:
  astro-doc-builder:
    build: ./builder
    volumes:
      - ./:/user_repo
      - ./dist:/astro-big-doc/dist
    container_name: astro-doc-builder
    cpu_count: 4     # Limit to specific number of CPUs
    mem_limit: 2048m  # Memory limit
