version: "3.8"

services:
  astro-doc-builder:
    build: ./builder
    volumes:
      - ./content:/user_repo/content
      - ./public:/user_repo/public
      - ./menu.yaml:/user_repo/menu.yaml
      - ./dist:/astro-big-doc/dist
    container_name: astro-doc-builder
